// Integration tests for lease operations
import { createTestLease, cleanupTestData, generateTestToken } from '../setup';

describe('Lease Operations', () => {
    let testData: any;

    beforeAll(async () => {
        testData = await createTestLease();
    });

    afterAll(async () => {
        if (testData?.lease) {
            await cleanupTestData(testData.lease.id);
        }
    });

    describe('Lease Creation via Helper', () => {
        test('should create a lease with correct tenant data', async () => {
            expect(testData.lease).toBeDefined();
            expect(testData.lease.id).toBeDefined();
            expect(testData.lease.tenantName).toBe('Test Tenant');
            expect(testData.lease.tenantEmail).toBe('test@example.com');
            expect(testData.lease.tenantPhone).toBe('555-0100');
            expect(testData.lease.status).toBe('ACTIVE');
        });

        test('should associate lease with property and unit', async () => {
            expect(testData.lease.propertyId).toBe(testData.property.id);
            expect(testData.lease.unitId).toBe(testData.unit.id);
            expect(testData.lease.unitName).toBe('TEST-1');
        });

        test('should have correct date range', async () => {
            const startDate = new Date(testData.lease.startDate);
            const endDate = new Date(testData.lease.endDate);

            expect(startDate.getFullYear()).toBe(2025);
            expect(endDate.getFullYear()).toBe(2025);
            expect(endDate > startDate).toBe(true);
        });

        test('should have a security deposit amount', async () => {
            expect(Number(testData.lease.securityDepositAmount)).toBe(2000);
        });
    });

    describe('Company Name Field', () => {
        test('should support companyName for commercial leases', async () => {
            const { prisma } = require('../../src/lib/accounting');

            const updated = await prisma.lease.update({
                where: { id: testData.lease.id },
                data: { companyName: 'Acme Warehousing LLC' }
            });

            expect(updated.companyName).toBe('Acme Warehousing LLC');

            // Read it back
            const fetched = await prisma.lease.findUnique({
                where: { id: testData.lease.id }
            });

            expect(fetched.companyName).toBe('Acme Warehousing LLC');
        });

        test('should allow null companyName for residential leases', async () => {
            const { prisma } = require('../../src/lib/accounting');

            const updated = await prisma.lease.update({
                where: { id: testData.lease.id },
                data: { companyName: null }
            });

            expect(updated.companyName).toBeNull();
        });
    });

    describe('Portal Token', () => {
        test('should have a portal token generated by createTestLease', async () => {
            expect(testData.lease.portalToken).toBeDefined();
            expect(testData.lease.portalToken).toContain('test-token-');
        });

        test('should have a portal token expiration date in the future', async () => {
            const expiresAt = new Date(testData.lease.portalTokenExpiresAt);

            expect(expiresAt > new Date()).toBe(true);
        });

        test('should generate unique tokens via generateTestToken', () => {
            const token1 = generateTestToken();
            const token2 = generateTestToken();

            expect(token1).not.toBe(token2);
            expect(token1).toContain('test-token-');
            expect(token2).toContain('test-token-');
        });

        test('should update portal token', async () => {
            const { prisma } = require('../../src/lib/accounting');

            const newToken = generateTestToken();
            const newExpiry = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days

            const updated = await prisma.lease.update({
                where: { id: testData.lease.id },
                data: {
                    portalToken: newToken,
                    portalTokenExpiresAt: newExpiry
                }
            });

            expect(updated.portalToken).toBe(newToken);

            const fetchedExpiry = new Date(updated.portalTokenExpiresAt);
            expect(fetchedExpiry > new Date()).toBe(true);
        });
    });
});
